build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 0
    CONAN_REFERENCE: "glfw/3.2"
    CONAN_USERNAME: "memsharded"
    CONAN_CHANNEL: "testing"
    CONAN_TOTAL_PAGES: 1

    matrix:
        - CONAN_CURRENT_PAGE: 1

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - python build.py
